# -*- coding: utf-8 -*-
"""Emotion_Recognition.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1AVa7GQKEHp1ltQcolXOfoMzLXsvKSMDD
"""

import tensorflow as tf
import pandas as pd
import matplotlib.pyplot as plt
import os
import kagglehub
import torch
from torch.utils.data import DataLoader, Dataset
from torchvision import datasets, transforms, models
from torch import nn
from torch.optim import Adam
from torch.utils.data import DataLoader, random_split

# device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
# print(device)

# Download latest version
path = kagglehub.dataset_download("samithsachidanandan/human-face-emotions")

print("Path to dataset files:", path)

for file in os.listdir(path):
  print(file)

file_path = os.path.join(path,"Data")
with os.scandir(file_path) as files:
  for file in files:
    print(file.name)

transform = transforms.Compose([
    transforms.Resize((128,128)),
    transforms.ToTensor(),
    transforms.Normalize(
        mean=[0.5,0.5,0.5],
        std=[0.5,0.5,0.5]
    )
])

dataset = datasets.ImageFolder(
    root=os.path.join(path, "Data"),
    transform=transform
)

print(dataset.classes)

print(dataset.class_to_idx)

print("Total Images:", len(dataset))

image, label = dataset[0]

print(image.shape)
print(label)
print(dataset.classes[label])

train_size = int(0.8 * len(dataset))
test_size = len(dataset) - train_size

train_dataset, test_dataset = random_split(
    dataset,
    [train_size, test_size]
)

train_loader = DataLoader(
    train_dataset,
    batch_size=32,
    shuffle=True
)

test_loader = DataLoader(
    test_dataset,
    batch_size=32,
    shuffle=False
)

images, labels = next(iter(train_loader))

print(images.shape)
print(labels)

import matplotlib.pyplot as plt
images, labels = next(iter(train_loader))
fig = plt.figure(figsize=(12,8))
for i in range(8):
    plt.subplot(2,4,i+1)
    img = images[i].permute(1,2,0)
    img = img * 0.5 + 0.5
    plt.imshow(img)
    plt.title(dataset.classes[labels[i]])
    plt.axis("off")
plt.show()





class CNN(nn.Module):
  def __init__(self):
    super(CNN, self).__init__()
    self.conv1 = nn.Conv2d(3, 16, 3, padding=1)
    self.conv2 = nn.Conv2d(16, 32, 3, padding=1)
    self.conv3 = nn.Conv2d(32, 64, 3, padding=1)
    self.pool = nn.MaxPool2d(2, 2)
    self.fc1 = nn.Linear(64 * 16 * 16, 512) # Corrected from 64 * 4 * 4
    self.fc2 = nn.Linear(512 , 5)
    self.relu = nn.ReLU()
    self.dropout = nn.Dropout(0.25)

  def forward(self, x):
    x = self.pool(self.relu(self.conv1(x)))
    x = self.pool(self.relu(self.conv2(x)))
    x = self.pool(self.relu(self.conv3(x)))
    x = x.view(-1, 64 * 16 * 16) # Corrected from 64 * 4 * 4
    x = self.dropout(x)
    x = self.relu(self.fc1(x))
    x = self.dropout(x)
    x = self.fc2(x)
    return x

model = CNN()
model.to(device)

model.eval()

optimizer = Adam(model.parameters(), lr=0.001)
criterion = nn.CrossEntropyLoss()

epochs = 10

for epoch in range(epochs):

    model.train()

    running_loss = 0
    correct = 0
    total = 0

    for images, labels in train_loader:


        optimizer.zero_grad()
        outputs = model(images)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item()
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
    train_loss = running_loss / len(train_loader)
    train_acc = 100 * correct / total
    print(
        f"Epoch [{epoch+1}/{epochs}] "
        f"Loss: {train_loss:.4f} "
        f"Accuracy: {train_acc:.2f}%"
    )



model.eval()
model.to(device) # Ensure model is on the correct device
correct = 0
total = 0
with torch.no_grad():
    for images, labels in test_loader:
        images = images.to(device)
        labels = labels.to(device)
        outputs = model(images)
        _, predicted = torch.max(outputs, 1)
        total += labels.size(0)
        correct += (predicted == labels).sum().item()
test_accuracy = 100 * correct / total
print(f"\nTest Accuracy : {test_accuracy:.2f}%")
# torch.save(
#     model.state_dict(),
#     "Emotion.pth"
# )

